# Generated by Django 4.1.7 on 2023-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Waiting approval', 'Waiting approval'), ('ACTIVE', 'ACTIVE'), ('Deleted', 'Deleted')], default='Active', max_length=40),
        ),
    ]
